// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi7WyTTqDIE44DijVlkGiHTUDVqxndr5k',
    appId: '1:646407546453:web:6ad9db6a8e777db78796dc',
    messagingSenderId: '646407546453',
    projectId: 'banco-desafio1',
    authDomain: 'banco-desafio1.firebaseapp.com',
    storageBucket: 'banco-desafio1.firebasestorage.app',
    measurementId: 'G-PBB4THHXR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmz-6NTb91nGGrEkaH20-kXXkoU5G6sBY',
    appId: '1:646407546453:android:bfcec49642205bce8796dc',
    messagingSenderId: '646407546453',
    projectId: 'banco-desafio1',
    storageBucket: 'banco-desafio1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-1FHe0dNNiv1YjKycLg44n7V1rH9B04',
    appId: '1:646407546453:ios:6f8b240b769370428796dc',
    messagingSenderId: '646407546453',
    projectId: 'banco-desafio1',
    storageBucket: 'banco-desafio1.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-1FHe0dNNiv1YjKycLg44n7V1rH9B04',
    appId: '1:646407546453:ios:6f8b240b769370428796dc',
    messagingSenderId: '646407546453',
    projectId: 'banco-desafio1',
    storageBucket: 'banco-desafio1.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
